server:
  port: 9093

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: naga-server
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:4306/naga?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update

custom:
  hadoop:
    rm:
      uri: 192.168.134.3:8088
    nn:
      uri: 192.168.134.3:50070
    conf: F:\java\hipeer\project\naga\naga-server\src\main\resources
    proxyUser: hadoop
    hivematestore: thift://192.168.134.3:9083
